### ISSUE TITLE
Pushing a new object in the array does not rerender the masonry

### ISSUE THREAD

**Issue by jayzyaj** [wynfred/ngx-masonry#10]
When I try to post an API request and get the response and push that object into the array. The masonry will not update even if I do a content resize on the viewChild.

**Comment by jorroll** [comment]
Have you tried creating a new array which contains the new object, and replacing the old array with that?

At first glance, this sounds like a known limitation of Angular's change detection, not an ngx-masonry bug. In general, change detection is done by object identity. When you push a new object into an array, the array's identity does not change.

**Comment by jayzyaj** [comment]
@thefliik My goal is to not refresh the whole array I just want to unshift the new object into the beginning or the top of masonry but it always display it at the bottom when I call the update`[updateLayout]="updateMasonryLayout"`.

**Comment by jorroll** [comment]
It sounds like you just said "my goal is not to change the array, I simply want to move things around in the array."

I'll point out the obvious, moving things around in the array *is changing the array*. For angular's `OnPush` change detection to work, you'll need to clone the array whenever you push things into it (this will tell Angular to run change detection again).

i.e
```typescript
updateMasonryLayout = [...updateMasonryLayout]
// or
updateMasonryLayout = updateMasonryLayout.slice()
```

At least I assume this is the problem you're running into.

Note, this is one of the reasons why folks use libraries like [NGRX](https://github.com/ngrx/platform).

edit:

You need to do this because, by default, angular evaluates input properties using `===`. And 
```typescript
const array = []
array.push(1)
array === array // so angular doesn't know that the array has changed
```

**Comment by jayzyaj** [comment]
@thefliik  so I would call the updateLayout and point it to the model array and made changes right?

**Comment by jorroll** [comment]
[It looks like](https://github.com/gethinoakes/ngx-masonry/blob/d389d6116e195b0a5b8dfc8d3f78c5666ca6236d/src/lib/ngx-masonry.component.ts#L82) you can pass *anything* into `[updateLayout]`, so long as that thing triggers change detection (i.e. is a new object). This is because all `updateLayout` appears to do is trigger a call to `this.layout()`. The value you pass to `updateLayout` isn't actually used for anything.

So it looks like whenever you want to update the layout, you can create a new object and pass it into updateLayout. I haven't actually used the updateLayout input property myself. Another, more advanced option, would be to get the `NgxMasonryComponent` using either `@ViewChild` or `@ContentChild` and call `.layout()` directly.

**Comment by jorroll** [comment]
Well at first glance that code looks good, and your use of `this.masonry.layout()` in the `setTimeout` callback should eliminate the need for `[updateLayout]="posts"` on `<ngx-masonry>`. You might try also calling `this.masonry.reloadItems()` at the same time you call `this.masonry.layout()`. I seem to remember in a few cases I found I needed to call both of them to get things working. Not sure if their order matters.

Unrelated, but if you only have one instance of a component in a view, you can specify a `@ViewChild` like
```
@ViewChild(NgxMasonryComponent) masonry: NgxMasonryComponent
```
And skip the need for the template reference variable. Won't work if you have multiple `NgxMasonryComponent` in the view though.

**Comment by jorroll** [comment]
If you're using `ChangeDetectionStrategy.OnPush`, the issue might be that you're not calling `this.changeDetectorRef.markForCheck()` within the component.

**Comment by jayzyaj** [comment]
The problem is even thou I used `unshift` to push the object at the beginning of the array it still pushes at the bottom of the content. I tried using `this.posts.slice(0, 0, post)` but still has no luck.

**Comment by jorroll** [comment]
It looks like ngx-masonry delegates to a `layout()` method within the masonry library itself to handle layout. Looking at the masonry library, it looks like html changes are appended (as opposed to prepended) to masonry's internal list of items. Looks like it's possible to [manually prepend new items (check out the `prepend` method)](https://masonry.desandro.com/methods.html), but looking at ngx-masonry's `add()` method, that's not something ngx-masonry supports. 

I think, since you've grabbed a handle to the ngx-masonry component, you can access the underlying masonry library directly from the `_msnry` property. Then you might be able to manually prepend your html element.

Also looks like this libraries `add()` method might of, at one point, [supported prepending](https://github.com/gethinoakes/ngx-masonry/blob/d389d6116e195b0a5b8dfc8d3f78c5666ca6236d/src/lib/ngx-masonry.component.ts#L107), but it doesn't at the moment. You might be able to make a PR to this library to add the functionality, if you figure out how to do it.

**Comment by hemangsk** [comment]
Hey @jayzyaj , were you able to find a fix for this issue? I'm facing the exact same problem of posts not ordered properly after sorting and change detection.

**Comment by madmacc** [comment]
@jayzyaj I have the same issue to and I tried most of the above before I found this.  Did you end up with a solution?

**Comment by jayzyaj** [comment]
@madmacc @hemangsk can't remember the algorithm or code we designed to achieve this. There are so many hacks that we did and it's not the best practice as I remember there are also lot of performance issue and we revamped the project on react but it gets the job done. Sorry guyss

**Comment by madmacc** [comment]
I actually just got it working using the following.
It redraws the masonry layout from scratch but otherwise it works fine.

```
         const newItemArray = [newItem];
          const oldArray = this.masonryArray;
          this.masonryArray= newItemArray;
          setTimeout(() => {
            this.masonryArray= this.masonryArray.concat(oldArray);
          }, 1000);
```

**Comment by madmacc** [comment]
This is an even better solution:
```
this.swipeFiles.unshift(newSwipeFile);
setTimeout(() => this.ngxMasonry._msnry.reloadItems());
this.updateMasonryLayout = Date.now().toString();
```

**Comment by madmacc** [comment]
@wynfred  Thanks, that is a much better solution.

**Comment by wynfred** [comment]
Updated readme with instructions - https://github.com/wynfred/ngx-masonry#faq
