### ISSUE TITLE
Cannot find module 'ngx-masonry'

### ISSUE THREAD

**Issue by quintonmiller** [wynfred/ngx-masonry#16]
Code: `import { NgxMasonryComponent, NgxMasonryOptions } from "ngx-masonry";`

This began occurring on 1.1.3. If we change to 1.1.2, the issue goes away. The package may just need to be re-published with code in master, as 1.1.2 was never committed and 1.1.3 contains lots of changes that were not committed.

**Comment by alipajand** [comment]
I was upgraded all of my packages to angular 8.1.1 and I also see that v1.1.3 is broken!
```Cannot find module 'ngx-masonry'```

```bash
import { NgxMasonryModule } from 'ngx-masonry';

@NgModule({
  imports: [
    NgxMasonryModule
  ]
})
```

**Comment by jorroll** [comment]
Dunno if this will help, but I maintain a separate angular library ([Angular IsLoadingService](https://gitlab.com/service-work/is-loading)) and I noticed this problem (`Cannot find module 'ngx-masonry'`) pop up in Angular 8. I was able to trace the issue to the `.metadata.json` file which ng-packagr produces when you bundle the library. For some reason the metadata file had incorrect filepaths saved inside it.

I was able to solve the issue by changing how I exported files. It's probably easiest if I just provide two examples:

This is my file structure:

```
src
  |- public_api.ts
  |- lib
     |- is-loading.service.ts
     |- module
        |- index.ts
        |- is-loading.module.ts
        |- directive
           |- index.ts
           |- // other files...
        |- pipe
           |- index.ts
           |- // other files...
```

When I was having issues, my `public_api.ts` file looked like:

```ts
export * from './lib/is-loading.service';
export * from './lib/module';
```
and `./lib/module/index.ts` looked like:

```ts
export * from './is-loading.module';
export * from './directory';
export * from './pipe';
```
You get the idea. Anyway, this structure caused some bug.

Changing `public_api.ts` to the following fixed the issue:

```ts
export * from './lib/is-loading.service';
export * from './lib/module/is-loading.module';
export * from './lib/module/directive/is-loading.directive.module';
export * from './lib/module/directive/is-loading.directive';
export * from './lib/module/directive/is-loading.directive.config';
export * from './lib/module/pipe/is-loading.pipe.module';
export * from './lib/module/pipe/is-loading.pipe';
```

Anyway, this might not be the issue here, but figured I'd share my experience given that you are seeing the same error message. You should be able to tell if this is the issue by examining the metadata.json file (of the distributed build) and making sure the filepaths it contains are correct.

**Comment by blodter** [comment]
Ran into the same problem - downgraded ngx-masonry to v1.1.2 and everything started functioning properly again.

**Comment by gethinoakes** [comment]
Apologies, I seem to have messed up the last release. I’m sure @wynfred will sort it soon 👍

**Comment by wynfred** [comment]
1.1.4 was released 🎊
