### ISSUE TITLE
 Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by txw8** [wynfred/ngx-masonry#20]
为何老报这个错呢?
包括这个https://ngx-masonry-demo.herokuapp.com/ 这个线上demo也很容易报错.
报错信息:
ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
希望能解决这个bug.

**Comment by txw8** [comment]
发现是ngx-masonry.component.ts文件中的add方法的this._element.nativeElement.removeChild(element);引起的, 需要判断element 为 this._element.nativeElement的子元素后, 再执行removeChild就不会报错了,但我无法推送分支, 所以还请作者改一下,谢谢!
                ......
		if (this.isParent(element, this._element.nativeElement)) {
			this._element.nativeElement.removeChild(element);
		}
                ......

	public isParent (obj, parentObj){
		while (obj != undefined && obj != null && obj.tagName.toUpperCase() != 'BODY'){
				if (obj == parentObj){
						return true;
				}
				obj = obj.parentNode;
		}
		return false;
	}

**Comment by wynfred** [comment]
Hi, thanks for reporting the issue! I'm using English because I want people who get the same exception and find this issue know what's happening here. Thank you for your PR but unfortunately I cannot accept it before further investigation is done.
So the problem seems like you are trying to add a tag that is outside of the masonry. But since you said that the online demo also has the same error, could tell me about what browser you are using? And it would be nice if you can provide a project on stackblitz.com that reproduces the problem so I can debug it.

**Comment by txw8** [comment]
Hi, Thank you for your reply me this question, I used the online demo you provided. The demo website is https://ngx-masonry-demo.herokuapp.com/ , I use Google Browser. You can see this picture. The same error occurred when I used this plug-in in my project.
(https://user-images.githubusercontent.com/23185097/64066394-953e1c80-cc4b-11e9-9de5-6aeead13aa9d.png)

**Comment by wynfred** [comment]
I still can't reproduce this issue. Could you tell me the version of your Chrome and try the online demo in the latest version/another browser?

**Comment by txw8** [comment]
I've upgraded my chrome to version 76.0.3809.132, but the console still will report the error when I hit the load button multiple times. The same error is reported with firefox.

**Comment by wynfred** [comment]
Oh you mean click the load button multiple times. Yeah now I can reproduce it. I think the issue is in the demo instead of the library. The demo uses the `filter` function which creates a new array to load new items. And when you click the button before the previous load is done, it tries to remove the element that was already removed.
The library can handle the error silently like the PR you submitted, but I think we should keep it. The error means the user of this library isn't loading the items correctly, and suppressing this error may cause a lot of unexpected behaviors.

**Comment by ssharma555** [comment]
> The error means the user of this library isn't loading the items correctly.

@wynfred Can you please describe the right way to load the items ? 
I am using infinite scroll and below is my code which is making use of  ngx-masonry:

>  <div class="masonry-demo">
    <ngx-masonry [options]="masonryOptions" [useImagesLoaded]="true"  (layoutComplete)="doStuff($event)" >
      <div ngxMasonryItem *ngFor="let d of page.data | async" class="masonry-item" >
        <app-item-card [data]="d"></app-item-card>
    
      </div>
    </ngx-masonry>
  </div>`

Here "page.data" is an observable and it gets updated when user scrolls to the bottom of the page.

I face the above issue intermittently and even after trying hard couldn't get around it. 
Can you please help me with this ? Thanks in Advance.

**Comment by wynfred** [comment]
@ssharma555 I'm not sure how you implemented the infinite scroll, but the idea is to not load items before the previous request is processed. You can add a flag like `this.isLoading`, set it to true when you scroll to bottom, set it to false in `layoutComplete` and only load new items when it's false.

**Comment by alecrt** [comment]
Same problem here, using infiniteScroll

**Comment by akropolis7** [comment]
Hello, i have this problem after update my angular project to 8 version, before i didn't have this problem

**Comment by etsraphael** [comment]
I got the same issue with infiniteScroll and angular 8

**Comment by ghost** [comment]
I'm experiencing the same issue: I am loading items synchronously because I want to keep the order of items. Imageloaded is set to true and I force the order by adding an item to an array when layoutcomplete is called. But still the error. Any ideas?

**Comment by Akiyamka** [comment]
Error still exist
